### ISSUE TITLE
Demo on your site crashes, using your project on my machine redirects to `https://dev.peterfiorella.com/`

### ISSUE THREAD

**Issue by CitralFlo** [PTRFRLL/spotify-song-export#1]
Hello, I wanted to export my playlist to .json using this project or demo on your website.

Demo on website crashes after clicking "download" button, with site not responding.

Project from github opened locally redirects to your website after authorization.

**Comment by PTRFRLL** [comment]
Hey there, to be honest this was a proof of concept project from a long time ago. I didn't even realize anyone was using it. This repo is actually for different but similar project. 

That said, my guess is you have a lot of playlists or a lot of songs in each playlist (or both).  I can try to devote some time to updating the playlist project soon. In the meantime, I pushed up the code to this repo: https://github.com/PTRFRLL/spotify-playlist-export. Feel free to submit a PR or fork it. I suspect the issue is we're putting too many callbacks on the call stack in the `getTracks` method: https://github.com/PTRFRLL/spotify-playlist-export/blob/main/js/app.js#L131
